# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish to Central Repository

# on:
#   release:
#     types: [created]
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checking in code
    - uses: actions/checkout@v3
    
    # https://github.com/actions/setup-java
    - name: Set up JDK 1.8
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '8'
    - run: java -version

#     - name: Build with Maven
#       run: mvn clean package

#     - name: Install gpg secret key
#       run: |
#         cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
#         gpg --list-secret-keys --keyid-format LONG
    
#     - id: publish-to-central
#     - name: Publish to Central Repository
#       env:
#         MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#         MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#       run: |
#         mvn \
#           --no-transfer-progress \
#           --batch-mode \
#           -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
#           clean deploy
