name: Maven Clean Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ershakiransari/jdk:8-mvn3

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.1.1

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress
